### PR TITLE
needs full path for windows

### PR DESCRIPTION
**Pull request by yutsuku**
On my windows 10 machine mpv and/or Explorer wasn't happy with filename only

### CODE REVIEW

**Comment by nimatrueway** [comment]
Thanks for contributing, but this logic is flawed. `working-directory` doesn't necessarily return directory of the opened file.

**Comment by nimatrueway** [comment]
I updated the code, you might wanna give it another go.

**Comment by yutsuku** [comment]
Works as long as there is no space character in path anywhere.
Tried to manually surround path part in single and double quotes with no luck. The following command seems to select file just fine (running from powershell).

`explorer /select,"D:\Video\AETEST\3366. space test.mp4"`

Is that issue with `subprocess_detached` method then?

**Comment by nimatrueway** [comment]
For me it's the `explorer.exe` having problem with double-quotes around "/select". I think I fixed it using `cmd`. Give updated version on `master` another try.

**Comment by yutsuku** [comment]
Works just fine, thanks!

**Pull request closed without merging**
